apiVersion: v1
kind: Service
metadata:
  name: svc-account
  labels:
    app: svc-account
spec:
  ports:
  - port: 29000
    targetPort: 29000
    protocol: TCP
  selector:
    app: svc-account

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: svc-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-account
  template:
    metadata:
      labels:
        app: svc-account
    spec:
      containers:
        - name: svc-account
          image: weikebala/filestore_grpc_k8s_account
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 29000
            name: accounts-port