apiVersion: v1
kind: Service
metadata:
  name: svc-apigw
  labels:
    app: svc-apigw
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: svc-apigw
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: svc-apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-apigw
  template:
    metadata:
      labels:
        app: svc-apigw
    spec:
      containers:
        - name: svc-apigw
          image: weikebala/filestore_grpc_k8s_apigw
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
            name: apigw-http-port