apiVersion: v1
kind: Service
metadata:
  name: svc-download
  labels:
    app: svc-download
spec:
  ports:
  - port: 29001
    targetPort: 29001
    protocol: TCP
    name: downloadrpc
  - port: 38080
    targetPort: 38080
    protocol: TCP
    name: downloadrest
  selector:
    app: svc-download
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: svc-download
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-download
  template:
    metadata:
      labels:
        app: svc-download
    spec:
      containers:
        - name: svc-download
          image: weikebala/filestore_grpc_k8s_download
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 29001
            name: downloadrpc
          - containerPort: 38080
            name: downloadrest
          volumeMounts:
          - mountPath: /data/fileserver
            name: file-volume
      volumes:
      - name: file-volume
        hostPath:
          path: /data/fileserver