apiVersion: v1
kind: Service
metadata:
  name: svc-dbproxy
  labels:
    app: svc-dbproxy
spec:
  ports:
  - port: 29003
    targetPort: 29003
    protocol: TCP
  selector:
    app: svc-dbproxy
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: svc-dbproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-dbproxy
  template:
    metadata:
      labels:
        app: svc-dbproxy
    spec:
      containers:
        - name: svc-dbproxy
          image: weikebala/filestore_grpc_k8s_dbproxy
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 29003
            name: dbproxy-port