apiVersion: v1
kind: Service
metadata:
  name: svc-upload
  labels:
    app: svc-upload
spec:
  ports:
  - port: 29002
    targetPort: 29002
    protocol: TCP
    name: uploadrpc
  - port: 28080
    targetPort: 29001
    protocol: TCP
    name: uploadrest
  selector:
    app: svc-upload
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: svc-upload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-upload
  template:
    metadata:
      labels:
        app: svc-upload
    spec:
      containers:
        - name: svc-upload
          image: weikebala/filestore_grpc_k8s_upload
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 29001
            name: uploadrpc
          - containerPort: 28080
            name: uploadrest
          volumeMounts:
          - mountPath: /data/fileserver
            name: file-volume
      volumes:
      - name: file-volume
        hostPath:
          path: /data/fileserver